version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: / # codedeploy-> ec2 넘긴 배포파일들이 모두 ec2 유저인 ec2-user 권한을 갖도록함
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks: # codedeploy 배포단계에서 실행할 명령어 지정
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료
      timeout: 60
      runas: ec2-user

  ApplicationStart: # applicationstart 단계에서 ec2-user 권한으로 nginx와 연결 않된 port로 새 버전의 스프링 부트를 시작
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인합니다
      timeout: 60
      runas: ec2-user
